Faq/urls.py
from django.urls import path
from .views import index
#url for app
urlpatterns = [
    path('', index),
]

Main/urls.py
from django.urls import path
from .views import index
#url for app

app_name = 'Main'
urlpatterns = [
    path('', index),
]

Register/urls.py
from django.urls import path
from .views import index
#url for app
urlpatterns = [
    path('', index),
]

Schedule/urls.py
from django.urls import path
from . import views

app_name = 'Schedule'
urlpatterns = [
	path('', views.index, name='index'),
	path('AddSchedule/', views.AddSchedule, name='AddSchedule'),
    path('saveSchedule/', views.saveSchedule, name='saveSchedule'),
    path('deleteAll/', views.deleteAll, name='deleteAll')
]

Story/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Main/', include('Main.urls')),
    path('Faq/', include('Faq.urls')),
    path('Register/', include('Register.urls')),
    path('Schedule/', include('Schedule.urls', namespace = 'Schedule')),
]

Faq/models.py
from django.db import models

# Create your models here.

Main/models.py
from django.db import models

# Create your models here.

Register/models.py
from django.db import models

# Create your models here.

Schedule/models.py
from django.db import models

class Schedule(models.Model):
	DAYS = (
		('Sunday', 'Sunday'),
		('Monday', 'Monday'),
		('Tuesday', 'Tuesday'),
		('Wednesday', 'Wednesday'),
		('Thursday', 'Thursday'),
		('Friday', 'Friday'),
		('Saturday', 'Saturday')
	)
	name = models.CharField(max_length = 20, )
	day = models.CharField(max_length = 10, choices=DAYS)
	date = models.DateField()
	time = models.TimeField()
	place = models.CharField(max_length = 20)
	category = models.CharField(max_length = 15)

Schedule/forms.py
from django import forms
from .models import Schedule
import datetime

class Schedule_Form(forms.ModelForm):
	class Meta: 
		model = Schedule
		fields = ('name', 'day', 'date', 'time', 'place', 'category')
		fields_required = ('name', 'day', 'date', 'time', 'place', 'category')
		widgets = {
			'name': forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'Activity name'}),
			'day' : forms.Select(attrs={'class' : 'form-control'}),
			'date' : forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
			'time' : forms.TimeInput(attrs={'type' : 'time', 'class' : 'form-control'}),
			'place' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'Activity place'}),
			'category': forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'Activity category'})
		}

	def clean_time(self):
		day = self.cleaned_data['day']
		date = self.cleaned_data['date']
		time = self.cleaned_data['time']
		date_time = ('%s %s' % (date, time))
		date_time = datetime.datetime.strptime(date_time, '%Y-%m-%d %H:%M:%S')
		date_day = date_time.strftime("%A")
		if datetime.datetime.now() >= date_time:
			self.add_error('date', "Wrong Date or Time!")
		if day != date_day:
			self.add_error('day', "Wrong Day!")
		return time

Faq/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'FaqPage.html')

Main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'MainPage.html')

Register/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'RegisterAccount.html')

Schedule/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Schedule
from .forms import Schedule_Form
from .models import Schedule

response = {}

def index(request):
	schedule = Schedule.objects.all().order_by('date', 'time')
	response['schedule'] = schedule
	return render(request, 'MySchedule.html', response)

def AddSchedule(request):
	response['form'] = Schedule_Form
	return render(request, 'Schedule.html', response)

def saveSchedule(request):
	form = Schedule_Form(request.POST or None)
	if (request.method == "POST" and form.is_valid()):
		response['name'] = request.POST['name']
		response['day'] = request.POST['day']
		response['date'] = request.POST['date']
		response['time'] = request.POST['time']
		response['place'] = request.POST['place']
		response['category'] = request.POST['category']
		schedule = Schedule(name=response['name'], day=response['day'], date=response['date'],
			time=response['time'], place=response['place'], category=response['category'])
		schedule.save()
		return HttpResponseRedirect('/../Schedule/')
	
	return render(request, 'Schedule.html', {'form':form})

def deleteAll(request):
	response['schedule'] = Schedule.objects.all().delete()
	response.clear()
	return HttpResponseRedirect('/../Schedule/')

Faq/templates/FaqPage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="Cover">
		<div class="Photo">
			<img src="http://anime-bump.com/wallpapers_peyz/121/08.jpg" 
				alt="cover"	class="Home_Cover" id="top">
		</div>
		<div class="Faq-Title">
			<b class="Title-Text">Frequently Asked Question</b>
		</div>
	</div>
	<div class="Faq-Content">
		<div class="FAQS">
			<div class="FAQ">
				<div class="row">
					<div class="Q-Box">
						<div class="Q-Box-2">
							<b class="Q"> Q </b>
						</div>
					</div>
					<p class="Question"> What genre of music do you listen to the most? </p>
				</div>
				<div class="row">
					<div class="A-Box">
						<b class=A> A </b>
					</div>
					<p class="Answer"> Jazz is my favorit genre! </p>
				</div>
			</div>
			<div class="FAQ">
				<div class="row">
					<div class="Q-Box">
						<div class="Q-Box-2">
							<b class="Q"> Q </b>
						</div>
					</div>
					<p class="Question"> Do you have a boyfriend? </p>
				</div>
				<div class="row">
					<div class="A-Box">
						<b class=A> A </b>
					</div>
					<p class="Answer"> No i don't </p>
				</div>
			</div>
			<div class="FAQ">
				<div class="row">
					<div class="Q-Box">
						<div class="Q-Box-2">
							<b class="Q"> Q </b>
						</div>
					</div>
					<p class="Question"> Why did you choose Computer Science as your major? </p>
				</div>
				<div class="row">
					<div class="A-Box">
						<b class=A> A </b>
					</div>
					<p class="Answer"> I don't know :o </p>
				</div>
			</div>
			<div class="FAQ">
				<div class="row">
					<div class="Q-Box">
						<div class="Q-Box-2">
							<b class="Q"> Q </b>
						</div>
					</div>
					<p class="Question"> How many children do you want? </p>
				</div>
				<div class="row">
					<div class="A-Box">
						<b class=A> A </b>
					</div>
					<p class="Answer"> Two children is enough </p>
				</div>
			</div>
		</div>
	</div>
{% endblock content %}

Main/templates/MainPage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="Profile">
		<div class="Photo">
			<img src="http://medchess.org/wp-content/uploads/2018/07/anime-background-wallpaper-hd-wallpaper.jpg" 
				alt="cover"	class="Home_Cover" id="pro">
			<img src="{% static "img/julia.jpg" %}" alt="photo" class="Profile_Photo">
		</div>
	</div>
	<div class="Profile2">
		<div class="Biodata">
			<div class="Biodata_Kiri">
				<div class="Name">
					<p class="Profile_Key">Name</p>
					<p class="Profile_Value">Julia Ningrum</p>
				</div>
				<div class="Address">
					<p class="Profile_Key">Address</p>
					<p class="Profile_Value">Jatinegara, Jakarta-Timur</p>
				</div>
			</div>
			<div class="Biodata_Kanan">
				<div class="Age">
					<p class="Profile_Key">Age</p>
					<p class="Profile_Value">18 Years Old</p>
				</div>
				<div class="E-mail">
					<p class="Profile_Key">E-mail</p>
					<p class="Profile_Value">Julia.ningrum@ui.ac.id</p>
				</div>
			</div>
		</div>
		<div class="Biodata2">
			<p class="Biodata2_Value">
				<i class="material-icons md-3">cake</i> Jakarta, July 27th 2000
			</p>
			<p class="Biodata2_Value">
				<i class="material-icons md-3">card_travel</i> College Student
			</p>
			<p class="Biodata2_Value">
				<i class="material-icons md-3" id="edu">chat</i> I Can Do It!
			</p>
		</div>
	</div>
	<div class="Education">
		<div class="Color-Box-Edu"></div>
		<p class="Edu-Title">Educational Background</p>
		<p class="Edu-Value">
			<i class="material-icons md-5">album</i> SDN Rawabunga 01 Pagi
		</p>
		<p class="Edu-Value">
			<i class="material-icons md-5">album</i> SMPN 36 Jakarta
		</p>
		<p class="Edu-Value">
			<i class="material-icons md-5">album</i> SMAN 54 Jakarta
		</p>
		<p class="Edu-Value">
			<i class="material-icons md-5" id="int">album</i> University of Indonesia
		</p>
	</div>
	<div class="Interests">
		<div class="Color-Box-Int"></div>
		<p class="Int-Title">Interests</p>
		<div class="Int-Row">
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://png.icons8.com/metro/1600/music.png" alt="music" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Music</p>
			</div>
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://cdn3.iconfinder.com/data/icons/black-easy/512/535112-game_512x512.png" alt="game" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Game</p>
			</div>
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://cdn3.iconfinder.com/data/icons/glypho-design/64/paint-brush-colors-artist-512.png" alt="art" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Art</p>
			</div>
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://educationatw.com/wp-content/uploads/2016/06/Languages-icon.png" alt="language" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Language</p>
			</div>
		</div>
		<div class="Int-Row">
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/62495-200.png" alt="coding" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Coding</p>
			</div>
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://cdn1.iconfinder.com/data/icons/nature-22/100/icon_leaf-leaves-double-01-512.png" alt="nature" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Nature</p>
			</div>
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://static.thenounproject.com/png/7433-200.png" alt="comic" class="Int-Icon-Image">
				</div>
				<p class="Int-Value">Comic</p>
			</div>
			<div class="Interest">
				<div class="Int-Icon">
					<img src="https://static.thenounproject.com/png/21701-200.png" alt="design" class="Int-Icon-Image">
				</div>
				<p class="Int-Value" id="ski">Design</p>
			</div>
		</div>
	</div>
	<div class="Skills">
		<div class="Color-Box-Ski"></div>
		<p class="Ski-Title">Skills</p>
		<div class="row">
			<p class="Ski-Value">Music</p>
			<div class="progress">
				<div class="progress-bar bg-info" style="width:80%;">80%</div>
			</div>
		</div>
		<div class="row">
			<p class="Ski-Value">Java</p>
			<div class="progress">
				<div class="progress-bar bg-info" style="width:50%;">50%</div>
			</div>
		</div>
		<div class="row">
			<p class="Ski-Value">Leadership</p>
			<div class="progress">
				<div class="progress-bar bg-info" style="width:80%;"">80%</div>
			</div>
		</div>
		<div class="row">
			<p class="Ski-Value">Multitasking</p>
			<div class="progress">
				<div class="progress-bar bg-info" style="width:90%;">90%</div>
			</div>
		</div>
		<div class="row" id="ach">
			<p class="Ski-Value">Reliability</p>
			<div class="progress">
				<div class="progress-bar bg-info" style="width:95%;" id="ach">95%</div>
			</div>
		</div>
	</div>
	<div class="Achievements">
		<div class="Top">
			<div class="Color-Box-Ach-L"></div>
			<p class="Ach-Title">Achievements</p>
			<div class="Color-Box-Ach-R"></div>
		</div>
		<div class="Ach-Boxes">
			<div class="Ach-Box">
				<div class="Box" id="Box-R">
					<img src="https://static.thenounproject.com/png/18791-200.png" alt="rubic" class="Ach-Icon">
				</div>
				<p class="Ach-Explanation" id="Expl-R"> 1st Place Rubik's Cube Competition Jambore 2012	</p>
			</div>
			<div class="Ach-Box">
				<div class="Box" id="Box-L">
					<img src="https://image.freepik.com/free-icon/kanji-character_318-37273.jpg" alt="jlpt" class="Ach-Icon">
				</div>
				<p class="Ach-Explanation" id="Expl-L"> Japanese-Language Proviciency Test N5 </p>
			</div>
			<div class="Ach-Box">
				<div class="Box" id="Box-R">
					<img src="https://png.icons8.com/money-bag/win8/1600" alt="treasurer" class="Ach-Icon">
				</div>
				<p class="Ach-Explanation" id="Expl-R"> Best SMAN 54 Organisation Treasurer 2015/2016 </p>
			</div>
			<div class="Ach-Box">
				<div class="Box" id="Box-L">
					<img src="https://static.thenounproject.com/png/14215-200.png" alt="finalist" class="Ach-Icon">
				</div>
				<p class="Ach-Explanation" id="Expl-L"> Finalist Primagama Smart Competition 2016 </p>
			</div>
			<div class="Ach-Box">
				<div class="Box" id="Box-R">
					<img src="https://s3.amazonaws.com/tinycards/image/130624b7f2694d8050c138bf584ec331" alt="un" class="Ach-Icon" >
				</div>
				<p class="Ach-Explanation" id="Expl-R"> 1st Place Rodoku Competition Bulan Bahasa SMAN 54 </p>
			</div>
			<p id="exp"></p>
		</div>
	</div>
	<div class="Experiences">
		<div class="Color-Box-Exp"></div>
		<p class="Exp-Title">Experiences</p>
		<div class="Exp_Text">
			<div class="Experience">
				<p class="Exp-Value">1. General Treasurer of Language Extracurricular (XBASS) SMAN 54</p>
				<p class="Exp-Expl">(2015-2016) Responsible for organisation's general financial oversight, financial planning and budgeting, financial reporting, and record keeping. </p>
			</div>
			<div class="Experience">
				<p class="Exp-Value">2. Latihan Dasar Kepemimpinan dan Pelantikan Anggota Baru XBASS Project Officer</p>
				<p class="Exp-Expl">(2016) Provides administrative and technical skills to support the project, and working with other team members to achieve project success.</p>
			</div>
			<div class="Experience">
				<p class="Exp-Value">3. Study Tour Bahasa Asing Secretary</p>
				<p class="Exp-Expl">(2016) Maintaning project effective records and administration to support and achieve project success </p>
			</div>
		</div>
	</div>
	<div class="Contact" id="con">
		<div class="Color-Box-Con"></div>
		<p class="Con-Title">Contact</p>
		<div class="Contacts">
			<div class="Contact-Left">
				<p class="Con-Value"><a href="https://wa.me/087885926091">
					<i class="fa fa-whatsapp"></i> 087885926091 </a>
				</p>
				<p class="Con-Value"><a href="https://www.facebook.com/julia.winx">
					<i class="fa fa-facebook-square"></i> Juliani Scarlet </a>
				</p>
			</div>
			<div class="Contact-Right">
				<p class="Con-Value"><a href="https://www.instagram.com/julianiscrlt/">
					<i class="fa fa-instagram"></i> julianiscrlt </a>
				</p>
				<p class="Con-Value"><a href="https://gitlab.com/Juliani27">
					<i class="fa fa-gitlab"></i> Juliani27 </a>
				</p>
			</div>
		</div>
	</div>
{% endblock content %}

Register/templates/RegisterAccount.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<div class="Cover">
		<div class="Photo">
			<img src="https://www.anibox.org/_nw/69/02349432.jpg" alt="cover" class="Home_Cover" id="top">
		</div>
		<div class="Reg-Title-Box">
			<b class="Title-Text">Register Account</b>
		</div>
	</div>
	<div class="Reg-Content">
		<div class="Reg-Title">
			<b class="Reg-Title-Text">Register For Free Account!</b>
		</div>
		<div class="Keys">
			<form action="#">
				<div class="form-group">
			    	<label for="name">Name :</label>
			    	<input type="text" class="form-control" id="name">
			  	</div>
			  	<div class="form-group">
			    	<label for="birth">Date of Birth :</label>
			    	<input type="date" class="form-control" id="birth">
			  	</div>
			  	<div class="form-group">
			    	<label for="email">Email address:</label>
			    	<input type="email" class="form-control" id="email">
			  	</div>
			  	<div class="form-group">
			    	<label for="username">User Name:</label>
			    	<input type="text" class="form-control" id="username">
			  	</div>
				<div class="form-group">
			    	<label for="password">Password:</label>
			    	<input type="password" class="form-control" id="password">
			  	</div>
			  	<div class="form-group">
			    	<label for="passwordC">Confirm Password :</label>
			    	<input type="password" class="form-control" id="password">
			  	</div>
			  	<button type="button" class="btn btn-danger btn-lg"><a href="#">Register</a></button>
			</form>
		</div>
	</div>
{% endblock content %}

Schedule/templates/MySchedule.html
{% extends 'base.html' %}
{% block content %}
	<div class="Cover">
		<div class="Photo">
			<img src="http://getwallpapers.com/wallpaper/full/1/d/6/75377.jpg" alt="cover" class="Home_Cover" id="top">
		</div>
		<div class="Sch-Title-Box">
			<b class="Sch-Title-Text">My Schedule</b>
		</div>
	</div>
	<div class="Sch-buttons">
		<button type="button" class="btn btn-success btn-lg" id="success2"><a href="{% url 'Schedule:AddSchedule' %}">Add Schedule</a></button>
		<button type="button" class="btn btn-danger btn-lg" id="danger2"><a href="{% url 'Schedule:deleteAll' %}">Delete All Schedule</a></button>
	</div>
	{% if schedule %}
	<div class="table-container">
		<div class="table-responsive-sm">
			<table class="table">
				<thead class="thead-dark">
					<tr>
			    	   	<th>Activity Name</th>
			       		<th>Day</th>
			       		<th>Date</th>
			        	<th>Time</th>
			        	<th>Place</th>
			        	<th>Category</th>
			      	</tr>
			    </thead>
			    <tbody>
			    	{% for data in schedule %}
			    	<tr>
				        <td>{{ data.name }}</td>
				        <td>{{ data.day }}</td>
				        <td>{{ data.date }}</td>
				        <td>{{ data.time }}</td>
				        <td>{{ data.place }}</td>
				        <td>{{ data.category }}</td>
				    </tr>
			    	{% endfor %}
			    </tbody>
			</table>
		</div>
	</div>
	{% else %}
		<div class="No-Sch">
			<p>You have no schedule</p>
		</div>
	{% endif %}
{% endblock content %}

Schedule/templates/Schedule.html
{% extends 'base.html' %}

{% block content %}
	<div class="Sch-Title-Box2">
		<p class="Sch-Title-Text2">Add Schedule</p>
	</div>
		<div class="Form">
			<div class="form-group">
				<form id="form" method="POST" action="{% url 'Schedule:saveSchedule' %}">
					{% csrf_token %}
		        	{{ form.as_p}}
					<button type="submit" class="btn btn-success btn-lg">Add Schedule</button>
				</form>
			</div>
		</div>
		<div class="clipart">
			<img src=https://openclipart.org/download/304826/1533580887.svg alt="photo" class="calendar">
		</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% load static %}
		<title>Julia Ningrum</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
	  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
	    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <link href='https://fonts.googleapis.com/css?family=Marck Script' rel='stylesheet'>
	    <link href='https://fonts.googleapis.com/css?family=Shadows Into Light' rel='stylesheet'>
		<link rel="stylesheet" type="text/css" href="{% static "css/Style.css" %}">
	</head>
	<body>
		<nav class="navbar navbar-expand-sm navbar-dark fixed-top">
	 		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
	    		<span class="navbar-toggler-icon"></span>
	  		</button>
			<div class="collapse navbar-collapse" id="collapsibleNavbar">
	    		<ul class="navbar-nav">
		    		<li class="nav-item dropdown">
	      				<a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">Profile</a>
	      				<div class="dropdown-menu">
	      					<a class="dropdown-item" href="\..\Main#pro">Top Profile</a>
					        <a class="dropdown-item" href="\..\Main#edu">Education</a>
					        <a class="dropdown-item" href="\..\Main#int">Interests</a>
					        <a class="dropdown-item" href="\..\Main#ski">Skills</a>
					        <a class="dropdown-item" href="\..\Main#ach">Achievements</a>
					        <a class="dropdown-item" href="\..\Main#exp">Experiences</a>
					        <a class="dropdown-item" href="\..\Main#con">Contact</a>
	      				</div>
	    			</li>
		    		<li class="nav-item">
		      			<a class="nav-link" href="\..\Faq">FAQ</a>
		    		</li>
		    		<li class="nav-item">
		      			<a class="nav-link" href="\..\Schedule">Schedule</a>
		    		</li>
		    	</ul>
		    	<button type="button" class="btn btn-info btn-lg ml-auto"><a href="\..\Register">Register</a></button>
	  		</div>
		</nav>
		{% block content %}
		{% endblock content %}
	</body>
</html>